<?php
/**
 * Redirect Assistant - Exporter.
 *
 * @package PressableCacheManagement
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Exporter for custom-redirects.php content.
 */
class PCM_Redirect_Assistant_Exporter {
	/**
	 * @param array $rules Rule list.
	 *
	 * @return array
	 */
	public function build_export( array $rules ): array {
		$rules    = array_values( array_map( 'pcm_redirect_assistant_sanitize_rule', $rules ) );
		$checksum = hash( 'sha256', wp_json_encode( $rules ) );
		$created  = gmdate( 'Y-m-d H:i:s' ) . ' UTC';

		$payload = array(
			'schema_version' => 1,
			'generated_at'   => $created,
			'checksum'       => $checksum,
			'rules'          => $rules,
		);

		$php  = "<?php\n";
		$php .= "/**\n";
		$php .= " * custom-redirects.php generated by Pressable Cache Management\n";
		$php .= " * Schema: 1\n";
		$php .= " * Generated: {$created}\n";
		$php .= " * Checksum: {$checksum}\n";
		$php .= " */\n\n";
		// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export -- Exporting generated PHP for a MU-plugin payload file.
		$php .= 'return ' . var_export( $payload, true ) . ';' . "\n";

		return array(
			'content' => $php,
			'meta'    => $payload,
			'syntax'  => $this->validate_syntax( $php ),
		);
	}

	/**
	 * @param string $php_content PHP source.
	 *
	 * @return array
	 */
	protected function validate_syntax( string $php_content ): array {
		$result = array(
			'valid'   => false,
			'message' => 'Syntax validation unavailable.',
		);

		if ( ! function_exists( 'sys_get_temp_dir' ) || ! defined( 'PHP_BINARY' ) ) {
			return $result;
		}

		$temp_file = trailingslashit( sys_get_temp_dir() ) . 'pcm-custom-redirects-' . wp_generate_uuid4() . '.php';
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Temporary syntax validation artifact in the system temp directory.
		$written = file_put_contents( $temp_file, $php_content );

		if ( false === $written ) {
			$result['message'] = 'Unable to write temporary file for syntax validation.';
			return $result;
		}

		$output = array();
		$code   = 1;

		// phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.system_calls_exec -- Uses the current PHP binary for optional syntax validation.
		exec( escapeshellarg( PHP_BINARY ) . ' -l ' . escapeshellarg( $temp_file ), $output, $code );
		wp_delete_file( $temp_file );

		$result['valid']   = ( 0 === $code );
		$result['message'] = implode( "\n", $output );

		return $result;
	}
}
